image: docker:stable-dind

stages:
  - test
  - build
  - deploy

build_image_job:
  stage: build
  image: google/cloud-sdk
  tags:
    - docker
  only:
    - /^DEV_.*$/
    - /^SIT_.*$/
    - /^PROD_.*$/
  script:
    - docker version
    - export
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud auth configure-docker
    - DOCKER_BUILDKIT=1 docker build -f ./build/Dockerfile -t gcr.io/dabenxiang226/kbc-cronjob:latest -t gcr.io/dabenxiang226/kbc-cronjob:$(git rev-parse HEAD) -t gcr.io/dabenxiang226/kbc-cronjob:$CI_COMMIT_TAG . --pull
    - docker image push gcr.io/dabenxiang226/kbc-cronjob:latest
    - docker image push gcr.io/dabenxiang226/kbc-cronjob:$(git rev-parse HEAD)
    - docker image push gcr.io/dabenxiang226/kbc-cronjob:$CI_COMMIT_TAG

deploy_helm_package:
  stage: deploy
  image: registry.silkrode.com.tw/team_golang/docker-library/deploy:3.1.0
  tags:
    - docker
  only:
    - /^DEV_.*$/
  environment:
    name: dev
    url: https://your-domain.com
  script:
    - apk add --no-cache curl
    # list k8s and helm repo
    - kubectl version
    - kubectl get pods --all-namespaces
    - helm repo list
    - helm repo update
    # list project
    - pwd
    - ls -all
    - helm upgrade mockserver deployments/helm
