apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
  namespace: kbc
  labels:
    app: mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
        - name: mockserver
          image: docker.io/yunchen/mockserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000