apiVersion: v1
kind: Service
metadata:
  name: mockserver
  namespace: kbc
  labels:
    app: mockserver
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32326
      protocol: TCP
      name: http
  selector:
    app: mockserver
